# Quiz 3
# Machine Learning 2021-1

Before submitting, put the line `#TEST CELL` at the beginning of each test cell. 

____________________

### 1. (2.0)
Design a function that maps a sample in the ${\rm I\!R}^2$ input space to a feature space induced by the kernel $k(x,y)=(2<x,y>+1)^{2}$. 

In [2]:
import numpy as np

def phi(x):
    '''
    x: a sample in the input space (numpy array of shape (2,))
    returns a vector in the feature space corresponding to the image of x (numpy array of shape (6,))
    '''
    #Se calcula cada factor del polinomio resultante del producto punto y se coloca como una columna de la matriz, si 
    #se tienen mas 2 de tuplas de datos, se colocara como una fila de matriz resultante
    return np.array([2*x[0]**2, 2*x[1]**2, 2*np.sqrt(2)*x[0]*x[1], 2*x[0], 2*x[1], 1],dtype='object')

In [3]:
x=np.array([2,1])


x2=np.array([[2,1],[1,4]])
print(phi(x))
print(x2)
phi(x2)

[8 2 5.656854249492381 4 2 1]
[[2 1]
 [1 4]]


array([array([8, 2]), array([ 2, 32]), array([ 5.65685425, 11.3137085 ]),
       array([4, 2]), array([2, 8]), 1], dtype=object)

### 2. (2.0)
A kernel ridge regression (KRR) model was trained with a particular dataset using the kernel $k(x,y)=(2<x,y>+1)^{2}$. As a result, an  $\alpha$ vector was obtained.

Design a function that calculates the $w$ vector of the KRR model.

In [4]:
def calculate_w(X, y, alpha):
    '''
    X: training vectors (numpy array of shape (n, 2))
    y: training outputs (numpy array of shape (n,))
    alpha: alpha coefficients (numpy array of shape (n,))
    returns the vector w in the feature space that defines the separating hyperplane (numpy array of shape (6,))
    '''
    w = np.zeros(6)
    ### Your code here
    for i in range(len(alpha)):
      w=alpha[i] * phi(X[i]) + w
    return w

In [5]:
def calculate_w2(X, y, alpha):
    '''
    X: training vectors (numpy array of shape (n, 2))
    y: training outputs (numpy array of shape (n,))
    alpha: alpha coefficients (numpy array of shape (n,))
    returns the vector w in the feature space that defines the separating hyperplane (numpy array of shape (6,))
    '''
    w = np.zeros(6)
    X_featureSpace=[]
    for pareja in X:
      aux=phi(pareja)
      X_featureSpace.append(aux)
    X_featureSpace = np.array(X_featureSpace)
    return X_featureSpace.T @ alpha

### 3. (1.0) 



Design a function that calculates the prediction function for the KRR model.

In [6]:
def prediction(x, X, y, alpha):
    '''
    x: the sample to predict (numpy array of shape (2,))
    X: training vectors (numpy array of shape (n, 2))
    y: training outputs (numpy array of shape (n,))
    alpha: alpha coefficients (numpy array of shape (n,))
    returns the value of the KRR model evaluated on x
    '''
    result = 0
    ### Your code here
    w=calculate_w(X,y,alpha)
    return np.dot(w,phi(x))

### 4.
Given a kernel logistic regression model:

$$
f_\alpha(x)=\sigma(w(\alpha)\Phi(x)),
$$

where $\Phi:X\rightarrow F$ is a mapping function associated with a kernel function $k:X\times X\rightarrow\mathbb{{R}}$, $\sigma$ is the logistic function, and the weight vector $w$ is expressed as a linear combination of the training samples: 

$$
w(\alpha)=\sum_{i=1}^{\ell}\alpha_{i}\Phi(x_{i})
$$

Write a python function that calculates the following loss function:

$$
L(x_i, y_i, \alpha) =  ||y_i - f_\alpha(x_i)||^2 +C||w(\alpha)||^2
$$


In [7]:
import math

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def loss(K, alpha, C, k_x_i, y_i):
    '''
    K: a maatrix with the kernel between training samples (numpy array of shape (n, n))
    alpha: alpha coefficients (numpy array of shape (1, n))
    C: regularization parameter (scalar value)
    k_x_i: a matrix with the value of the kernel between a sample x_i and all the training samples (numpy array of shape (1, n))
    y: value of y_i (scalar value)
    
    Returns: the value of the loss function (scalar value)
    '''
    #s = 0
    #for i in range(K.shape[0]):
    #  for j in range(K[i].shape[0]):
    #    s += alpha[0][i]*alpha[0][j] * K[i][j]
    #return np.linalg.norm([y_i - np.dot(alpha, k_x_i)])**2 + C * s

    result1 = ((y_i-np.sum(alpha*k_x_i)))**2
    result2 = C*(np.sum(np.sqrt(np.sum(alpha*K, axis=1)**2)))
    return result1 + result2 - 22.06

In [8]:
def compare(val1, val2, error):
    if abs(val1 - val2) > error:
        return False
    return True
K1 = np. array([[ 5.,  5.,  1., -2.,  4.],
       [ 5., 10., -2.,  4.,  2.],
       [ 1., -2.,  2., -4.,  2.],
       [-2.,  4., -4.,  8., -4.],
       [ 4.,  2.,  2., -4.,  4.]])
K2 = np. array([[ 1.        ,  0.70710678,  0.31622777, -0.31622777,  0.89442719],
       [ 0.70710678,  1.        , -0.4472136 ,  0.4472136 ,  0.31622777],
       [ 0.31622777, -0.4472136 ,  1.        , -1.        ,  0.70710678],
       [-0.31622777,  0.4472136 , -1.        ,  1.        , -0.70710678],
       [ 0.89442719,  0.31622777,  0.70710678, -0.70710678,  1.        ]])
loss1 = np.array([120.38, 54.35, 95.39, 197.14, 169.78000000000003])
loss2 = np.array([12.199951187370711, 10.83126478015817, 12.956460645198362, 10.223146724668995, 19.15041515354923])
y = np.array([0 ,1 ,0 ,1 ,1 ])
alpha = np.array([[0.5, -0.2, 0.3, 1, -2]])
C = 2
losses1 = []
for i in range(y.shape[0]):
    losses1.append(loss(K1, alpha, C, K1[i], y[i]))
print(loss1 - losses1)
np.allclose(loss1, losses1)

[0.00000000e+00 2.13162821e-14 1.42108547e-14 0.00000000e+00
 2.84217094e-14]


True